sudo: false
dist: trusty
language: python
cache:
    pip: true
matrix:
    include:
        - python: 3.5
          env: TEST_MODE=PEP8
        - python: 3.5
          env: TEST_MODE=PEP257
        - python: 3.5
          env: TEST_MODE=PYLINT
        - python: 3.6
          env: TEST_MODE=PEP8
        - python: 3.6
          env: TEST_MODE=PEP257
        - python: 3.6
          env: TEST_MODE=PYLINT
    allow_failures:
        - python: 3.5
          env: TEST_MODE=PYLINT
        - python: 3.6
          env: TEST_MODE=PYLINT
install:
    - pip install -U pip wheel
    - pip install -q pytest pytest-xdist pytest-cov python-coveralls coverage pytest-timeout
    - pip install -q pep8 pytest-pep8
    - pip install -q pylint pytest-pylint
    - pip install -q pydocstyle
    - pip install -q -r requirements.txt
script:
    - if [[ "$TEST_MODE" == "PEP8" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
      elif [[ "$TEST_MODE" == "PEP257" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH pydocstyle;
      elif [[ "$TEST_MODE" == "PYLINT" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH py.test --pylint -m pylint -n0;
      fi
after_success:
    - coveralls
